### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by markisoke** [corbinmunce/domoticz-plex-webhook#2]
When running this on Ubuntu 16.04 I'm getting the following error:

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
`

**Comment by corbinmunce** [comment]
What version of Node are you running?  I'm using v7.10 on my Raspberry Pi.

**Comment by partymike** [comment]
I'm seeing something similar running node 8.9.1 - will this be supported or should I downgrade?

**Comment by corbinmunce** [comment]
adding "use strict" to the top of main.js gets rid of this error.  when running on Ubuntu you may need to add sudo in front of the command, ie "sudo node main.js" or "sudo nodejs mainjs"
